# Generated by Django 5.1.6 on 2025-12-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
