# Generated by Django 5.1.6 on 2025-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ziina_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
