# Generated by Django 5.1.6 on 2025-12-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_ziina_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ziina_payment_id',
        ),
    ]
