# Generated by Django 5.1.6 on 2025-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('section_title', models.CharField(max_length=200)),
                ('section_text', models.TextField()),
                ('feature_title', models.CharField(max_length=200)),
                ('feature_text_1', models.TextField()),
                ('feature_text_2', models.TextField()),
                ('feature_image', models.ImageField(upload_to='about/')),
                ('promise_title', models.CharField(max_length=200)),
                ('promise_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
