# Generated by Django 5.1.6 on 2025-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactpage_contactservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactservice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
