# Generated by Django 5.1.6 on 2025-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(upload_to='homepage/')),
                ('season_tag', models.CharField(default='SPRING / SUMMER 2024', max_length=100)),
                ('hero_title', models.CharField(default='Ethereal', max_length=100)),
                ('hero_subtitle', models.CharField(default='Elegance', max_length=100)),
                ('explore_button_text', models.CharField(default='EXPLORE COLLECTION', max_length=50)),
                ('watch_button_text', models.CharField(default='WATCH CAMPAIGN', max_length=50)),
                ('announcement_1', models.CharField(default='Complimentary Shipping on Orders Over AED 200', max_length=200)),
                ('announcement_2', models.CharField(default='Sustainably Sourced Materials', max_length=200)),
                ('announcement_3', models.CharField(default='Handcrafted in Provence', max_length=200)),
                ('featured_image_1', models.ImageField(upload_to='homepage/featured/')),
                ('featured_label_1', models.CharField(default='Style Inspiration', max_length=100)),
                ('featured_image_2', models.ImageField(upload_to='homepage/featured/')),
                ('featured_label_2', models.CharField(default='Fine Details', max_length=100)),
                ('featured_image_3', models.ImageField(upload_to='homepage/featured/')),
                ('featured_label_3', models.CharField(default='New Collection', max_length=100)),
                ('newsletter_title', models.CharField(default='Join the Inner Circle', max_length=200)),
                ('newsletter_subtitle', models.TextField(default='Subscribe to receive early access to new collections, exclusive events, and sustainable fashion news.')),
                ('newsletter_button_text', models.CharField(default='Subscribe', max_length=50)),
                ('footer_brand_description', models.TextField(default='Timeless elegance inspired by nature. Sustainable fashion for the thoughtful wardrobe.')),
                ('footer_newsletter_title', models.CharField(default='Stay in Bloom', max_length=100)),
                ('footer_newsletter_description', models.TextField(default='Subscribe for new arrivals and exclusive offers.')),
                ('footer_newsletter_button', models.CharField(default='Join', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
    ]
