# Generated by Django 5.2.8 on 2025-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='announcement_3',
            field=models.CharField(default='Handcrafted in UAE', max_length=200),
        ),
    ]
