# Generated by Django 5.2.8 on 2025-12-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='signin_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/auth/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='signup_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/auth/'),
        ),
    ]
