# Generated by Django 5.1.6 on 2025-12-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmessage_is_read_contactmessage_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='watch_button_url',
            field=models.URLField(blank=True, help_text='URL for the campaign video (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
