# Generated by Django 5.1.6 on 2025-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homepage_watch_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp')], max_length=20, unique=True)),
                ('url', models.URLField(help_text='Full URL to your social media profile')),
                ('is_active', models.BooleanField(default=True, help_text='Show this social media link in footer')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
    ]
