# Generated by Django 5.2.8 on 2025-12-17 10:11

import django.db.models.deletion
from django.db import migrations, models, connection


def migrate_color_data_forward(apps, schema_editor):
    # Create Color objects
    Color = apps.get_model('store', 'Color')

    color_data = {
        'Lavender': '#E6E6FA',
        'Purple': '#800080',
        'Dark': '#000000',
        'Beige': '#F5F5DC',
        'White': '#FFFFFF',
    }

    # Create Color objects
    for color_name, hex_code in color_data.items():
        Color.objects.create(name=color_name, hex_code=hex_code)


def migrate_color_data_reverse(apps, schema_editor):
    # This would be for reversing the migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_care_product_material_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(migrate_color_data_forward, migrate_color_data_reverse),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color'),
        ),
    ]
