# Generated by Django 5.1.6 on 2025-12-17 10:19

import django.db.models.deletion
from django.db import migrations, models, connection
from django.utils.text import slugify


def create_categories_and_update_products(apps, schema_editor):
    # Create Category objects
    Category = apps.get_model('store', 'Category')

    category_data = [
        'Dresses',
        'Tops',
        'Bottoms',
        'Knitwear',
        'Sets',
    ]

    # Create Category objects
    category_objects = {}
    for category_name in category_data:
        category, created = Category.objects.get_or_create(name=category_name, defaults={'slug': slugify(category_name)})
        category_objects[category_name] = category

    # Update Product records using raw SQL
    cursor = connection.cursor()

    for category_name, category_obj in category_objects.items():
        cursor.execute("""
            UPDATE store_product
            SET category = %s
            WHERE category = %s
        """, [category_obj.id, category_name])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_color_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(create_categories_and_update_products),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
