# Generated by Django 5.1.6 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for category display', null=True, upload_to='categories/'),
        ),
    ]
