# Generated by Django 5.1.6 on 2025-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, help_text='Group products with same design but different colors/sizes', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this category (recommended size: 300x350px for best display on homepage)', null=True, upload_to='categories/'),
        ),
    ]
